image: androidsdk/android-32

pipelines:
  default:
    - step:
        name: Gastro CICD
        caches:
          - gradle
        script:
          - ./gradlew assembleLoungeproNoretailWhiteDebug
        artifacts:
          - app/build/outputs/**